# Generated by Django 2.1 on 2019-03-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('date', models.DateField()),
                ('contestID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
