# Generated by Django 2.1 on 2019-03-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='contestID',
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
