# Generated by Django 2.1 on 2019-04-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contestHost',
            field=models.CharField(default='Mike', max_length=264),
        ),
        migrations.AddField(
            model_name='contest',
            name='contestName',
            field=models.CharField(default='Foxtrot', max_length=264),
        ),
        migrations.AddField(
            model_name='contest',
            name='theme',
            field=models.CharField(default='Alpha', max_length=264),
        ),
    ]
