# Generated by Django 2.1.7 on 2019-04-15 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0005_auto_20190413_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 4, 15, 5, 30, 22, 15588, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 15, 11, 0, 22, 15588)),
        ),
    ]
