# Generated by Django 2.1.7 on 2019-04-15 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0006_auto_20190415_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 15, 11, 12, 51, 813374)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 4, 15, 5, 42, 51, 813374, tzinfo=utc)),
        ),
    ]
